apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-shell
  template:
    metadata:
      labels:
        app: example-shell
    spec:
      containers:
      - name: example-shell
        image: headforwards/example-shell:latest
